### ISSUE TITLE
Create Dashboard Route

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#10]
### Description
A new route for the dashboard needs to be created in the application. This route should initially render an empty page, serving as a placeholder for future content and features.

### Requirements
- **Route Creation:** Implement a new route for the dashboard (e.g., `/dashboard`).
- **Empty Page:** The initial page should be blank with minimal content.

### Technical Considerations
- Follow existing project conventions for file structure and naming.

### Tasks
1. Create a new file for the dashboard route in the appropriate directory.
2. Implement a simple functional component that renders an empty page.

### Notes
This page will be updated in future iterations as additional features and content are developed.

**Comment by KodeSage** [comment]
Can I take care of this issue?


My background and how it can be leveraged 

I'm a Software Engineer with over 4+ years of  demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development and Solidity, and Cairo/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust and external Projects like Passage, Stellar, etc. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements. With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

 I'm excited to bring this experience and drive for innovation to your team.


Implementation Plan:

Route Creation
Introduce a new route for /dashboard in the routing configuration.
Ensure seamless integration with the existing route structure.
File Structure and Naming
Create a new file (e.g., Dashboard.js or Dashboard.tsx) in the appropriate directory for page components.
Follow project conventions for organization, naming, and file structure.
Component Implementation
Implement a simple functional component to render an empty page.
Include minimal styling (if applicable) to indicate the placeholder state.
Future-Proof Design
Write clean and modular code that is easy to extend for future dashboard features.
Add comments to guide future development.
I estimate completing the task in 1 day.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Alfred-Emmanuel** [comment]
Why i think i'm the right person for this

I am a software engineer(frontend) with 4 years of hands on experience and i am an avid open source contributor, i also participated in the just concluded hacktoberfest,
the ETA for this if i'm assigned to it would be 48hrs

**Comment by pheobeayo** [comment]
Could I be assigned to this?

I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.
I will tackle this issue by following the routing used in the codebase and render the dashboard page

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by myspace20** [comment]
For a simple issue like this, I can provide a solution within an hour. I would like to work on this as soon as possible.

**Comment by Unickhub** [comment]
Can I work on this, please?

**Comment by omsant02** [comment]
i would like to take this issue

i am a new contributor to this repo and want to start my contribution journey with Paystell, also i have knowledge of nextjs and page router
ETA : 2 days
Thank you

**Comment by Jemiiah** [comment]
Step 1: Create the Dashboard Component
I’ll create a new file for the dashboard route in the proper directory. For instance, if it's a React project, I'll place it in `src/routes` or `src/pages`.

Example: Basic Functional Component
Here’s what I’ll add for the placeholder dashboard:

```
// src/pages/Dashboard.tsx or src/routes/Dashboard.tsx

import React from 'react';

const Dashboard = () => {
  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome to the dashboard! This page is under construction.</p>
    </div>
  );
};

export default Dashboard;

Step 2: Set Up the Dashboard Route
I’ll then add this new route to the application’s routing configuration.

React Router Example:
If the project uses React Router, I’ll modify the routing in `App.js` or `App.tsx`:


````import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Dashboard from './routes/Dashboard';

const App = () => {
  return (
    <Router>
      <Routes>
        {/* Other routes */}
        <Route path="/dashboard" element={<Dashboard />} />
      </Routes>
    </Router>
  );
};

export default App;```

Next.js Example:
If the project is built with Next.js, I’ll create a new file named dashboard.tsx in the pages directory:


```// pages/dashboard.tsx

const Dashboard = () => {
  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome to the dashboard! This page is under construction.</p>
    </div>
  );
};

export default Dashboard;
```

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


I will create a new route that will lead to the dashboard if the user is an admin using the if statement.

glad to work on this 
Thanks

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by ryzen-xp** [comment]
May I be assigned to this?

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---
