### ISSUE TITLE
Implement List of Payment Links

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#11]
### Description
A section for displaying a list of payment links needs to be created within the dashboard. This section should include a "+ New Link" button positioned in the top right corner, following the design guidelines provided in Figma.

### Requirements
- **List Display:** The section must display existing payment links in a clear and organized manner.
- **Button Placement:** Include a "+ New Link" button at the top right of the section for adding new payment links.
### Technical Considerations
- Use **TailwindCSS** for styling and layout to maintain consistency with the rest of the application.
- Ensure that components are implemented using **shadcn/ui** and **Radix UI** for enhanced user experience.
### Tasks
1. Design the structure for the list of payment links.
2. Style the list and button using TailwindCSS classes.

### Figma Reference
You can use the Figma design linked [here](https://www.figma.com/design/jmGSfuyhg1ger0yWBTxES3/PayStell-Dashboard?m=auto&t=6qcP1zY6JCdYWxLL-1) as a reference, but feel free to use the previously mentioned components as a guide.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Mystic-Nayy** [comment]
May I pick this up?

**Comment by petersdt** [comment]
Can I start working on this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to continue contributing and supporting the development of this project.

How I Plan on Tackling This Issue
I will create a section within the dashboard to display the list of payment links using components from shadcn/ui and Radix UI, following the Figma design.
I will position the "+ New Link" button at the top right.
I will style the list and button using TailwindCSS.
I will test the functionality to ensure everything works correctly.

**Comment by myspace20** [comment]
I can deliver a timely and efficient solution for this issue with a max ETA of 5hrs.

**Comment by Benjtalkshow** [comment]
Is it okay if I take this?

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by Michaelkingsdev** [comment]
Can I take this from here?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by CtpN3m01** [comment]
**Hello! 👋**
My name is Saymon Porras Briones, and I am a passionate Software Developer with experience in creating responsive and user-friendly interfaces. As a member of the Dojo Coding community, I am always looking for opportunities to contribute to meaningful projects and hone my skills.

This issue aligns perfectly with my interests and expertise, and I am excited about the opportunity to implement the List of Payment Links feature. Below is a breakdown of how I would approach this task to ensure it meets the described requirements and maintains consistency with the application's current design and functionality.

**📌 Proposed Plan**
1. List Display
I will design and implement the structure for the payment links list, ensuring a clean and organized presentation that aligns with the Figma design reference.
The list will support scalability and adaptability for different screen sizes, using TailwindCSS utility classes to ensure responsive behavior.

2. "+ New Link" Button Placement
The "+ New Link" button will be placed precisely in the top-right corner of the section, following the design guidelines.
I will ensure that the button is styled consistently with the rest of the application and utilizes interactive states (hover, active, disabled) for an intuitive user experience.

**🎨 Styling Approach**
Leverage TailwindCSS for precise and consistent styling throughout the section.
Incorporate components from shadcn/ui and Radix UI to ensure accessibility and enhanced user experience.

**✅ Technical Deliverables**
Functional List Component: A React component to display payment links dynamically, retrieving the data from the backend or a mock API.
Responsive Design: Ensuring that the list and button work seamlessly on all screen sizes, maintaining usability and aesthetic quality.
Reusable Components: Wherever possible, the implementation will prioritize creating reusable components to simplify future maintenance and enhancements.
Integration Ready: The feature will be designed to integrate seamlessly into the existing dashboard without disrupting other components.

**📂 Verification Steps**
Validate the list and button placement against the Figma design to ensure alignment with visual and functional expectations.
Test for responsiveness across different devices and screen sizes.
Conduct usability testing to ensure smooth interaction with the "+ New Link" button and the list itself.

**🚀 Final Thoughts**
I am confident in my ability to deliver a high-quality implementation of this feature while adhering to the project's design and technical standards. I look forward to contributing to this project and collaborating with the team to bring this feature to life.

Thank you for considering my application for this issue. Please let me know if there's any additional information or clarification you'd like!

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by KevinLatino** [comment]
Hello! My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I will create a dashboard section to display a list of payment links, styled with TailwindCSS for consistency. A "+ New Link" button will be positioned at the top right, following the Figma design. The implementation will use ShadCN UI and Radix UI for enhanced usability and aesthetics.
