### ISSUE TITLE
Form to Create New Payment Links

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#12]
### Description
A form needs to be created for adding new payment links. This form should include input fields for the necessary details: name, currency, price, SKU or ID, and an option to upload a featured image.

### Requirements
- **Input Fields:**
  - **Name:** A text input for the name of the product or service. 
  - **Currency:** A dropdown or select input to choose the currency.
  - **Price:** A numeric input field for the price of the item or service.
  - **SKU or ID:** A text input for entering the SKU or unique identifier.
  - **Featured Image:** An upload input to allow users to select and upload an image that represents the payment link.
- **Responsive Design:** Ensure that the layout is responsive and user-friendly across different devices.
- **Validation:** Implement basic validation for required fields (e.g., name, price).

### Technical Considerations
- Use **TailwindCSS** for styling and layout to maintain consistency with the rest of the application.
- Ensure that components are implemented using **shadcn/ui** and **Radix UI** for enhanced user experience.
- Follow TypeScript conventions for form handling and validation.

### Tasks
1. Design the layout of the form for creating new payment links with appropriate input fields.
2. Implement each input field with necessary props and validation logic.
3. Style the form using TailwindCSS classes to ensure a cohesive design.

### Notes
This form will be integrated into the payment link creation workflow and should align with existing design patterns in the application. This is just a design, the button to create a new link should not do any function for now.

### Figma Reference
You can use the Figma design linked [here](https://www.figma.com/design/jmGSfuyhg1ger0yWBTxES3/PayStell-Dashboard?m=auto&t=6qcP1zY6JCdYWxLL-1) as a reference, but feel free to use the previously mentioned components as a guide.

**Comment by Mystic-Nayy** [comment]
May I handle this issue?
 i am a frontend developer 
i will use ShadCN UI components (e.g., Input, Select) with TailwindCSS classes to build a responsive form for name, currency, price, SKU, and image upload.
Manage state and validation using TypeScript, ensuring required fields like name and price have basic checks.

**Comment by jaykayudo** [comment]
Could I take over this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by starknetbrother** [comment]
Could I try solving this?

**Comment by myspace20** [comment]
I am a developer with over two years of experience and I can handle this issue in less than 10hrs.

**Comment by KevinLatino** [comment]
Hello @MPSxDev My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I'll design a responsive form for creating new payment links, with fields for name, currency, price, SKU/ID, and a featured image upload. The form will be styled with TailwindCSS, using shadcn/ui and Radix UI components for a smooth experience. Basic validation will be added for required fields like name and price. The "Create Payment Link" button will be non-functional for now, and I'll follow the Figma design for consistency.

Here is an example of a Frontend Project that I have made: 
https://buildmyevent.xyz/

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Can I work on this, please?

**Comment by Michaelkingsdev** [comment]
I’d like to help with this.

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. I'd love to give this a go

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by mimisavage** [comment]
May I try my hand at this?

**Comment by hossamanany** [comment]
Can I attempt this issue?

**Comment by Jethrolopwus** [comment]
Hi, I'm Jethro Lopwus a react.js/next.js front end developer. I will want to implement this form and validate the necessary input fields using react-hook-form react package.
also I will style using tailwind css classes. please I will be glad to implement this as a first contributor.
