### ISSUE TITLE
Make Settings Page

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#14]
### Description
A settings screen needs to be created that allows users to update their profile information. This includes changing their name, uploading a logo or profile picture, and editing their description.

### Requirements
- **Input Fields:**
  - **Name:** A text input field for the user to enter or update their name.
  - **Logo/Profile Picture:** An upload input that allows users to select and upload an image file for their logo or profile picture.
  - **Description:** A text area for users to provide or update a brief description about themselves or their business.
- **Responsive Design:** Ensure that the layout is responsive and user-friendly across different devices.
- **Validation:** Implement basic validation for required fields (e.g., name).

### Technical Considerations
- Use **TailwindCSS** for styling and layout to maintain consistency with the rest of the application.
- Ensure that components are implemented using **shadcn/ui** and **Radix UI** for enhanced user experience.

### Tasks
1. Design the layout of the settings screen with appropriate input fields.
2. Implement each input field with necessary props and validation logic.

### Notes
This settings screen will allow users to personalize their profiles and improve their experience within the application. This is just for design, save buttons should not store any input for now.

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

To address this issue, I propose the following steps:

Design and Layout

Use TailwindCSS to create a responsive layout that adapts seamlessly to different screen sizes.
Structure the layout with clear sections for the input fields:
Name field (text input).
Logo/Profile Picture upload field.
Description field (textarea).
Include proper spacing, alignment, and aesthetic consistency with the rest of the application.
Input Fields and Validation

Implement the input fields using shadcn/ui and Radix UI components for an enhanced user experience.
Add validation logic to ensure required fields are filled (e.g., the Name field cannot be empty).
For the Logo/Profile Picture field:
Include file type and size validation to guide users during upload.
For the Description field:
Set a reasonable character limit and provide visual feedback for users.
Responsive Design

Test the layout on various devices and screen sizes to ensure optimal usability.
Adjust styles using TailwindCSS utilities (e.g., grid, flex, and responsive modifiers like sm, md, lg).
Implementation Notes

Focus on building a fully functional UI with mock interactions since the save button will not persist data for now.
Ensure accessibility by adding ARIA labels, keyboard navigation, and focus states where needed.
Deliverables:

A visually appealing, functional settings screen with responsive design.
Input fields with basic validation logic.
A clean, maintainable codebase that adheres to the project's style and component guidelines.
take this issue?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Kingsuite** [comment]
Let me handle this issue!

**Comment by Unickhub** [comment]
Let me try this one!

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

I would like to contribute to this project for the first time and bring my skills to this amazing initiative. I have extensive experience with TailwindCSS and front-end development, and I’ll ensure the settings screen is responsive, user-friendly, and aligned with your design system.

To solve this issue, I will:

Design a responsive layout 
Implement input fields for name, profile picture/logo upload, and description with basic validation.
Follow all guidelines and ensure the screen is consistent
Pls Feel free to reach out!

**Comment by KevinLatino** [comment]
Hello @MPSxDev My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar.

I'll create a responsive layout with the required fields using TailwindCSS for styling, and integrate shadcn/ui and Radix UI for enhanced functionality and user experience. The input fields will include a text input for the name, an image upload field for the logo/profile picture, and a text area for the description. Basic validation will be added for the name field, ensuring it is required. The layout will be designed to adapt to different screen sizes. As this is a design-focused task, the buttons will not store any input data for now.

Here is an example of a Frontend Project that I have made: 
https://buildmyevent.xyz/

**Comment by omsant02** [comment]
Could I take over this issue?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
I’d like to work on this.

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer.

**Comment by stephanniegb** [comment]
I’d like to help with this. I have extensive experience building responsive, performant, and secure web pages. I’ve worked with many frontend tools, including TailwindCSS, RadixUI, and ShadCN.
Here are some of my latest projects for reference:
- https://tba-frontend-eta.vercel.app
- https://scroll-transform-recreate.vercel.app
- https://three-js-galaxy-silk.vercel.app/

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. Please can i address this issue

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with experience in both front-end and back-end development, and I would love to tackle this issue. With my proficiency in TypeScript and experience working on the front-end aspects of my last few hackathons, I'm confident that I can contribute to this project efficiently.

My workflow:

- Design responsive settings screen with input fields
- Add name, image upload, and description inputs
- Implement validation for required fields
- Use TailwindCSS, shadcn/ui, and Radix UI for styling

ETA: 48 hrs

**Comment by DanielEmmanuel1** [comment]
Would love to tackle this!

I plan to design the Settings Screen by following this steps

- I'll Input fields for Name, Logo/Profile Picture upload, and a Description text area.

- Create a Responsive layout styled with TailwindCSS for usability across devices.

- Make a Basic validation for required fields like Name.

- I plan to utilize TailwindCSS, shadcn/ui and Radix UI for a seamless user experience.

ETA: 48 hours.

**Comment by Yunusabdul38** [comment]
I’d like to work on this,
and make sure it meets the requirements

**Comment by ikezuby2012** [comment]
I am a full-stack software engineer with expertise in building dynamic web portals and dashboards. My skillset includes React, Next.js, Tailwind CSS, and ShadCN UI, which I use to create efficient and user-friendly applications. My estimated time of delivery for most projects is just three days. To see an example of my work, you can explore my project here: [Fitness King](https://fitnessking.vercel.app/).

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by ikezuby2012** [comment]
I am a full-stack software engineer with expertise in building dynamic web portals and dashboards. My skillset includes React, Next.js, Tailwind CSS, and ShadCN UI, which I use to create efficient and user-friendly applications. My estimated time of delivery for most projects is just two days. To see an example of my work, you can explore the project here: [Fitness King](https://fitnessking.vercel.app/).

i also plan to use formik or react-hook-form to hande the form and input validation

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by t0fudev** [comment]
Hello! My name is t0fudev, and I am a computer science student and Web3 developer with some experience working on the frontend of various projects. I am eager to leverage my skills and contribute to this exciting project.

I am interested in working on the settings page, implementing the required features according to the project description, and ensuring an attractive, easy to use, functional, and responsive design.

I would be grateful for the opportunity to contribute to this issue and make a meaningful impact. Thank you for considering my application. I truly appreciate your time and consideration.

**Comment by t0fudev** [comment]
Hello! My name is t0fudev, and I am a computer science student and Web3 developer with some experience working on the frontend of various projects. I am eager to leverage my skills and contribute to this exciting project. 

I am interested in working on the settings page, implementing the required features according to the project description, and ensuring an attractive, easy to use, functional, and responsive design. And if there's any doubt on the process I would ask inmmediately to maintainers for help.

I would be grateful for the opportunity to contribute to this issue and make a meaningful impact. Thank you for considering my application. I truly appreciate your time and consideration.

ETA: 48 hrs.

**Comment by esladan** [comment]
I'd like to handle this task.

**Comment by SudiptaPaul-31** [comment]
Would love to solve this issue

My approach to tackle this issue:

Using Tailwindcss for styling and layout to ensure responsiveness. Align input fields in a user-friendly vertical format.
Utilizing shadcnui components and Radix UI for input fields.
Name: Text input with required field validation.
Logo/Profile Picture: File upload input with basic styling.
Description: Textarea with placeholder and character limit.
Validation: Add basic validation for required fields using props like required.
Responsiveness: Test on different device sizes to confirm a seamless user experience.

**Comment by mimisavage** [comment]
May I take this issue on?

**Comment by Jemiiah** [comment]
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks i have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

**Comment by Rayguti** [comment]
Why I’m Interested: This feature aligns well with my experience in UI/UX design and frontend development. I am excited to contribute to improving the user experience by providing a customizable settings interface that will enhance the app's personalization features. Additionally, working with TailwindCSS, shadcn/ui, and Radix UI will allow me to apply best practices in styling and component implementation.

Proposed Approach:

    Design and Layout:
        Create a responsive layout for the settings screen that ensures the input fields are displayed clearly and intuitively across different devices.
        The design should be simple, user-friendly, and align with the rest of the application’s design guidelines.

    Input Fields:
        Name Field:
            Create a text input field that allows users to enter or update their name.
            Implement basic validation to ensure that the name field is not empty when submitting (required field validation).
        Logo/Profile Picture Upload:
            Create an image upload input that allows users to upload a profile picture or logo.
            Implement an image preview so users can see the selected file before submission.
        Description Field:
            Add a text area where users can enter or update their brief description.
            Implement basic validation for the description to ensure it's not empty (required field).

    Responsive Design:
        Use TailwindCSS to style the settings screen and input fields.
        Ensure that the layout adjusts appropriately to different screen sizes, from mobile devices to desktop.

    Component Implementation:
        Use shadcn/ui and Radix UI components to ensure a high-quality user experience, with components like modals or tooltips for better interaction and guidance.
        For now, the inputs will not store any values, and save functionality will be added later.

    Validation Logic:
        Ensure basic validation is implemented for the required fields, such as checking if the name or description is not empty.
        Display clear error messages when validation fails.

    UI Testing:
        Test the settings screen layout and validation across multiple devices to ensure the design is responsive and functional.

    Follow Project Guidelines:
        Follow the project's guidelines for design consistency and code structure.
        Ensure the implementation is modular, with reusable components.

Outcome: The settings screen will allow users to update their profile information, including their name, profile picture/logo, and description. The design will be responsive, and the user experience will be enhanced using shadcn/ui and Radix UI components. Basic validation will be implemented for required fields, providing a smooth and intuitive settings experience.

**Comment by emarc99** [comment]
I am a new contributor.

I will clone the, check the UI or ask for figma design.
Install any shadcn component and libraries required.
Build the UI pitch perfect according to the design, breaking reusable/re-rendering parts into components.
Use Tailwind for styling and uniform responsiveness across different screens.
Testing, then build to ensure no errors.

ETA - 1 day
