### ISSUE TITLE
Sales Section to Display Sales Data

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#15]
### Description
A Sales section needs to be created that allows users to view their obtained sales and total sales over specified periods. This section should present the data in a simple and clear manner, utilizing shadcn/ui components for consistency and ease of use.

### Requirements
- **Sales Data Display:**
  - Show a list of obtained sales with relevant details (e.g., date, amount, item sold).
  - Display the total sales amount for selected periods (e.g., daily, weekly, monthly).
- **Period Selection:** Include options for users to filter the sales data by different time periods.
- **Responsive Design:** Ensure that the layout is responsive and user-friendly across different devices.

### Technical Considerations
- Use **shadcn/ui** components as a guide for building the UI elements. Feel free to explore the distribution of components available in shadcn/ui to enhance the user experience.

### Tasks
1. Design the layout for the sales section, including filters and data display components.
2. Implement functionality to fetch and display sales data based on user-selected time periods.
3. Style the section using TailwindCSS classes and shadcn/ui components for a cohesive look.

### Notes
This section will provide users with valuable insights into their sales performance and should be designed with simplicity and clarity in mind. **This is just the design, for now I used fake data to show the design.**

**Comment by mimisavage** [comment]
I can handle this task , kindly assign.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Alfred-Emmanuel** [comment]
**Why i think i'm the right person for this**

I am a software engineer(frontend) with 4 years of hands on experience and i am an avid open source contributor, i also participated in the just concluded hacktoberfest,
the ETA for this if i'm assigned to it would be 48hrs
**

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by myspace20** [comment]
I'd like to take this issue.

**Comment by Unickhub** [comment]
Could I grab this task?

**Comment by KevinLatino** [comment]
Hello @MPSxDev My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I'll design a layout that displays sales data using shadcn/ui components for consistency and TailwindCSS for styling. The section will include filters for selecting time periods (daily, weekly, monthly) and a clear display of the obtained sales, including details like date, amount, and item sold. I'll ensure the layout is responsive for different devices. For now, I'll use fake data to showcase the design, and functionality for fetching and displaying real sales data will be implemented later. The design will focus on simplicity and clarity to ensure a smooth user experience.

Here is an example of a Frontend Project that I have made: 
https://buildmyevent.xyz/

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer.

**Comment by 0xdevcollins** [comment]
Can I try solving this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by KoxyG** [comment]
Hi,  

I am applying through OnlyDust to contribute to this project. I can design and build the Sales section to display sales data clearly and effectively.  

I will:
- Create a responsive layout using **shadcn/ui components**.
- Add filters for users to view sales by daily, weekly, and monthly periods.
- Display a list of sales and total sales in a simple, user-friendly way.
- Use **TailwindCSS** for styling and include fake data to focus on the design.  

This section will provide users with clear insights into their sales. I look forward to contributing.

**Comment by Jemiiah** [comment]
Hello ser I can work this issue

**Comment by Psalmuel01** [comment]
I'm Samuel, a proficient web3 frontend developer with experience in ui design. I am that developer that totally obsesses over delivering pixel perfect screens.

I am meticulous about it, and I work very fast as well. My frontend skills are  also excellent, and my codebase clean. I am also very familiar with shadcn ui, and will excellently implement it.

I have taken a look at the project, and this is a task I can very well handle. I would maintain styling consistency and accurately deliver all milestones to the T.

I would love to contribute my expertise to this project. Kindly let me.

**Comment by JamesVictor-O** [comment]
I'd like to take this issue? I'm a frontend developer who is proficient with javascript and typscript  with react and next.js framework and good in creating responsive and visually appealing webdesigns, i would appreciate it if i am been given this issue to work on with an ETA of maximum two days.
