### ISSUE TITLE
Payment Links Screen Design

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#16]
### Description
A payment links screen needs to be created that displays essential information for customers to complete their purchases. This screen should include the logo and name of the business, the total amount to be paid, the product title, and a "Pay" button.

### Requirements
- **Business Profile:**
  - Display the business logo prominently on one side of the screen.
  - Include the name of the business next to or below the logo.
- **Payment Information:**
  - Show the total amount to be paid clearly.
  - Display the title of the product being purchased.
- **Call to Action:**
  - Include a prominent "Pay" button that initiates the payment process.
- **Responsive Design:** Ensure that the layout is responsive and user-friendly across different devices.

### Technical Considerations
- Use **[Figma](https://github.com/PayStell/paystell-website/blob/main/DASHBOARD_DESIGN.md)** as a design reference for layout and styling. See the screen called `Payment`.

### Tasks
1. Design the layout for the payment links screen, incorporating branding elements and payment details.
2. Implement each component using shadcn/ui and Radix for enhanced user experience and interactivity.
3. Style the screen using TailwindCSS classes to ensure a cohesive design with existing application styles.
4. Test responsiveness across different devices to ensure usability.

### Notes
This is just the design for now, you should not perform any action.

**Comment by Michaelkingsdev** [comment]
@MPSxDev 
I am an experienced fullstack developer. I am comfortable with using nextjs/typescript and shadcn.
Can this issue be assigned to me?

I will design and implement the Payment Links screen to display business branding, payment details, and a clear "Pay" call-to-action. Using the Figma design as a reference, I’ll create the layout with Radix and shadcn/ui for interactivity and style it with TailwindCSS for consistency with the application. The design will be responsive, ensuring usability across all devices, and will focus solely on the layout without any functional actions at this stage.

I will make PR in 24hrs.

**Comment by 0xdevcollins** [comment]
I'd like to handle this task.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would like to contribute for first time to the project, so I can bring my abilities to this amazing project. I also have a huge background in talwindCSS and frontend.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!

**Comment by Unickhub** [comment]
Can I attempt this issue?

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by MrRoudyk** [comment]
Can I work on this, please?

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. Can  i help in solving this task

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by Yunusabdul38** [comment]
I’d like to work on this,
and make sure it meets the requirements

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by ikezuby2012** [comment]
I am a full-stack software engineer with expertise in building dynamic web portals and dashboards. My skillset includes React, Next.js, Tailwind CSS, and ShadCN UI, which I use to create efficient and user-friendly applications. My estimated time of delivery for most projects is just three days. To see an example of my work, you can explore the project here: [Fitness King](https://fitnessking.vercel.app/).

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this

**Comment by blessingbytes** [comment]
I am a frontend and blockchain developer specializing in creating intuitive user interfaces . I have experience with modern frameworks like React and smart contract development on platforms like Ethereum and Starknet.
 
Pls i would love to tackle this issue

**Comment by dslegacy** [comment]
As a seasoned UI designer with over three years of experience in the Blockchain space and six years in the web2 space, I am confident in my ability to deliver high-quality solutions.

My expertise spans designing intuitive and visually appealing interfaces that cater to diverse user needs. I'd love to bring my skills to this project and contribute to its success.

For a glimpse into my design capabilities, please find some samples of my previous work:

https://www.figma.com/design/Aoqja6gAE8C6K5jpFC0v1R
https://www.figma.com/design/i3lki1OQcC9hq8IXVoPKeK
https://www.figma.com/design/h0jTwDuM6TcNaBCBcpcZ8a
https://www.figma.com/design/NjsQRMgHlul0amZZQXr9HO

**Comment by hossamanany** [comment]
Is it okay if I tackle this?

**Comment by aniruddhaaps** [comment]
To address this issue
I should use Figma as a reference, design a responsive payment links screen, ensuring appropriate placement of the business logo, name, payment details, and the "Pay" button.
Implement this layout using Radix and shadcn/ui for interactivity, with styles for consistency with the rest of the application with TailwindCSS.
Focus on a clean and user-friendly design, optimized for all sizes, clear branding, and a focus on a call to action.

**Comment by 0xdevcollins** [comment]
May I be assigned to this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by bruhhgnik** [comment]
Hi, 

I’d like to work on this issue. I have experience with Figma, TailwindCSS, Radix, and shadcn/ui, and can create a responsive, user-friendly design aligned with the requirements. I’ll ensure the business logo, payment details, and "Pay" button are prominently displayed, with a cohesive layout and styling. 

Looking forward to your approval to start!

Thank you!

**Comment by Majormaxx** [comment]
Hi, 
I'm a front end developer. I'll be glad if I'm assigned this issue my ETA for this issue is 5 hours.

**Comment by od-hunter** [comment]
Hi can I work on this design issue please? I have vast experience with ui/ux design and I’m up to the task. Kindly assign me.

**Comment by Dhir0808** [comment]
May I handle this issue?

**Comment by Wilfred007** [comment]
My name is Wilfred, I am a frontend developer with years of working experience, I will solve this issue with react, tailwindcss and use shadcn components to make a responsive design.

**Comment by emarc99** [comment]
Can I handle this task? Let me do this, sir. ETA - 2 days max.

**Comment by emmz3230** [comment]
I'd like to handle this task.
I will like to interpret the design using my front-end web developer styling skills, such as CSS and Tailwind CSS, with the ShadcnUI for this design.
 i will interpret this design using the figma file and the properties therein, like the font size and width and making it responsive.

**Comment by CEOliam** [comment]
I'd like to take this issue.

**Comment by Jemiiah** [comment]
@MPSxDev I'm a frontend web3 developer with over 75+ onlydust contributions in past OD hacks. please i would love to handle this issue with an ETA of 48 hoursmax

**Comment by jahrulezfrancis** [comment]
I’d love to work on this! I can create a clean, responsive payment links screen that ticks all the boxes. Let me know if I should get started!

**Comment by Agbeleshe** [comment]
I would love to be assigned this issue please. I have numerous experience creating responsive designs  I will be able to  create this payment screen design within a day

**Comment by Supa-mega** [comment]
Can I take care of this issue? first time contributor

**Comment by omsant02** [comment]
i would like to work on this issue,

experienced with nextjs, also a first time contributor on this repo and would like to start contribution journey

ETA : 12 hrs

**Comment by akintola4** [comment]
Can I take care of this issue?

**Comment by OlgaKush512** [comment]
Hello,
My name is Olga, and I am a frontend developer. I work with Figma and would be happy to take on this task.
Being a frontend developer, I have a strong understanding not only of the design aspect but also the technical side of implementation.
My stack includes TypeScript, JavaScript, React, Angular, and C#.
