### ISSUE TITLE
Create a Markdown (MD) template for PRs

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#2]
- Create a Markdown file.
- Include important and mandatory details to fill out when proposing a PR.
- Feel free to suggest a template.

**Comment by derianrddev** [comment]
Hi, I'm Derian, a fullstack developer and I'm Dojo Coding member.

Previously, I participated in creating the template for PRs for the Semaphore Stellar documentation project and ByteBeastFrontend, and I would like to contribute to this project.
