### ISSUE TITLE
Finalize Flows and Design in Figma

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#22]
### Description
Complete the design and user flows in **Figma**, ensuring all screens and interactions are well-defined and visually cohesive. The objective is to provide a clear guide for stakeholders and developers.

### Requirements
- **Flows:**
  - Clearly outline all user steps with arrows and annotations for transitions.
- **Screen Design:**
  - Finalize visuals for all screens, using placeholders or real content where needed.
- **Components:**
  - Create reusable components and include interaction states (hover, active, disabled).

### Technical Considerations
- Align designs with branding guidelines.

### Tasks
1. Review and refine existing designs in Figma.
2. Finalize user journey flows and screens.
3. Create reusable components with interaction states.
4. Prototype the flow to simulate interactions.
5. Upload a file with the link to Figma in the PR

### Notes
Focus on design and flow creation only; no implementation tasks are required.

**Comment by od-hunter** [comment]
Hi @MPSxDev , can I do this please? I’m up for the task.
