### ISSUE TITLE
Design and Implement Login Screen

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#38]
## 📘 Description
Design and implement the login screen for the application, enabling users to access their accounts using their credentials.

## 🔍 Steps

1. Design and implement a login screen with fields for email, password, and optional 2FA.
2. Add functionality for the "Forgot Password" link (optional; for now, it should redirect to a placeholder page).
3. Ensure the login button matches the styling of the primary button component, is fully functional, and includes proper user input validation.
4. Validate responsiveness and accessibility to provide a seamless experience across all devices.

## ✅ Acceptance Criteria

- Validation is in place for email and password fields.
- The screen is fully responsive and accessible.
- Components must be reusable and organized in the login folder.

**Comment by JamesVictor-O** [comment]
Good day, I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I will Design and Implement Login Screen using Shadcn UI ,Tailwind CSS and react hookform, within an estimated 26 hours.

**Comment by derianrddev** [comment]
**Hello PayStell team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your project during the **Only Dust #11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue* **"Design and implement the login screen"**

1. **Design and functionality:**
    - Create a form with fields for **email** and **password**.
    - Include an optional field for **two-factor authentication (2FA)**.
    - Implement a **"Forgot Password"** link (which redirects to a placeholder page for now).
    - Ensure the **login button** has the primary button styling and is fully functional with proper user input validation.
2. **Validations:**
    - Validate **email** and **password** fields to ensure the email format is correct and the password is valid.
3. **Responsiveness and accessibility:**
    - Ensure the screen is fully **responsive** and **accessible** on all devices.
4. **Component organization:**
    - Components must be **reusable** and organized within the **login** folder.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by MarcusDavidG** [comment]
Is it okay if I tackle this? with my solid experience with web3 frontend design and knowledge of how smart contracts work, this issue should be as sweet as a piece of cake lol

**Comment by respp** [comment]
Hello! I am Renzo: www.renzobarcos.site
I have been exploring the repository and its issues these past days, and I felt that I could add value to applications that focused on component design. I am confident that I can bring value to this issue as well.
I am part of the Dojo community and am excited about the opportunity to make my first contributions to Paystell.

In addition to my experience as a frontend and full-stack developer, I have a strong understanding of UI/UX principles, which will allow me to design and implement a login screen that is visually appealing, fully responsive, and accessible. I will:

*  Design a visually appealing and responsive login screen with fields for email, password, and optional 2FA.
* Add a functional "Forgot Password" link that redirects to a placeholder page.
* Implement robust input validation to ensure correct user data handling.
* Create reusable components organized within the login folder to maintain consistency.

I will ensure that all requirements described in the issue are met and that the final result aligns perfectly with the acceptance criteria, delivering high-quality, user-focused functionality.

Thank you for the opportunity 🚀!

**Comment by psychemist** [comment]
Hello. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

I will tackle this issue using these steps:

- Design and implement the login screen layout, including fields for email, password, and an optional 2FA field.
- Add functionality for the "Forgot Password" link, which will redirect to a placeholder page in the meantime
- Ensure the login button matches the primary button styling and implement full functionality with input - validation for email and password fields.
- Validate the email and password inputs to ensure proper formatting and validation.
- Make the login screen fully responsive across devices and ensure it meets accessibility standards.
- Organize all components to be reusable and structured within the login folder for maintainability and scalability.


I aim to complete this task within 24 hours after being assigned and setting up my development environment, with my first pull request submitted before 12 hours. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you.

**Comment by mimisavage** [comment]
Could I take on this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Can i work on this?

**Comment by ShantelPeters** [comment]
Mind if I try this one?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by codeZe-us** [comment]
Could I take over this issue?

**Comment by od-hunter** [comment]
Hello ser, please can I be assigned this issue? I am an experienced ui/ux designer and here is proof of some designs I've done.
https://github.com/PayStell/paystell-website/issues/22,
https://github.com/mubarak23/chainevents-frontend/issues/6.

I have experience in in html, css, JavaScript, TypeScript and cairo.

I've gone through the description and I promise to follow the steps. I'll come up with a clean and user centric design

Kindly assign me please, I'm up for the task.

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I would design and implement a clean login screen with fields for email and password, including a "Forgot Password" link that redirects to a placeholder page for now. The login button would match the primary button style and be fully functional, ensuring proper validation for both email and password inputs. I would ensure the screen is fully responsive, adapting to different device sizes, and accessible, with clear labels and focus states for users with disabilities. Components would be organized within a dedicated login folder for better maintainability. Finally, I would test the functionality, responsiveness, and accessibility to ensure a seamless user experience.

**Comment by jahrulezfrancis** [comment]
I would really love to work on this task. I’ll design and implement the login screen with email, password, and optional 2FA fields. It will include proper validation, a functional "Forgot Password" link (redirecting to a placeholder), and a responsive, accessible design. Components will be reusable and well-organized in the login folder.

I can have this done within 24 to 36 hours.

**Comment by TheSQLguy** [comment]
So, I will create the login screen with fields to input email, password, and optional 2FA fields. The "Forgot Password" link will redirect to a placeholder page for now. The login button will style like the primary button but will have validation on all user inputs. The login screen will be responsive across all devices, and its components will be kept in a login folder for easy reusability.

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.


To tackle this issue:

I’ll design and implement a login screen with fields for email, password, and optional 2FA.
Add a "Forgot Password" link redirecting to a placeholder page.
Ensure proper validation for inputs, responsiveness, and accessibility.
Organize reusable components in the login folder for modularity.
ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will Include fields for email, password, and an optional 2FA input, and implement a "Forgot Password" link redirecting to a placeholder page for now. Ensure the login button adheres to the styling of the primary button component and supports functionality with proper input validation for the email and password fields.

**Comment by Supa-mega** [comment]
I'd love to work on this!

**Comment by wheval** [comment]
Can I jump on this task?

**Comment by obah** [comment]
Hi, I am Obaloluwa, a frontend developer with over 2 years of experience, using React, NextJs, typescript and tailwindCSS regularly and I am well familiar with creating pages like the one in this task.

Can I work on this issue?

My plan to handle this issue:
1. I will study the design to know all the requirements and components I need to create, then familarize myself with the code base to get the structure and tools used.
2. Next is I will create all the required ui components for this screen, including the form, ensuring they are resuable, responsive, accessible and match the design perfectly.
3. Then, implement the screen for this task, ensure its functional and the login form validation is effective.
4. Finally, implement all the other required functionality like forgot password and features "normal" on a login page

ETA: 1 to 2 days.

I will be sure to communicate with the team on telegram if I face any blockers and would create a PR once I am done.

**Comment by emmz3230** [comment]
Can I take this from here?

Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will create the login form from the Figma design, making it have validation hereby making it responsive and resuable as a component

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by KevinLatino** [comment]
Hi, I’d like to work on this issue. I’ll design and implement a responsive login screen with email, password, and optional 2FA fields. The "Forgot Password" link will redirect to a placeholder page, and the login button will follow the primary button styling with proper validation. Components will be reusable and organized in the login folder, ensuring accessibility and responsiveness across devices.
