### ISSUE TITLE
Create Main Dashboard Screen

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#39]
## 📘 Issue Description
Implement the main dashboard for the application. The dashboard should display a summary of the user's latest activity and the total sales balance.

## 🔍 Steps

1. Analyze the design requirements for the dashboard based.
2. Create a layout that includes:
 -Section for recent activity (e.g., recent transactions or actions).
 -Section for displaying the total sales balance prominently.
3. Develop reusable components for:
 -Activity list or cards.
 -Balance display (e.g., with currency formatting).
4. Integrate dummy data for testing purposes and ensure it is easily replaceable with real data in the future.
5. Validate responsiveness and accessibility across devices.

## ✅ Acceptance Criteria

- The dashboard matches the design specifications.
- Recent activity is displayed in a clear and organized manner.
- Total sales balance is displayed prominently with proper formatting.
- The design is fully responsive and accessible.
- Components must be reusable and organized in the dashboard folder.

## 🌎 References
![image](https://github.com/user-attachments/assets/d050b73c-15d8-4a01-899d-029feadd80de)

## 📜 Additional Notes
It’s important to implement it as a separate component. Review how the other sections are structured to ensure consistency across components.

**Comment by JamesVictor-O** [comment]
Good day, I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I will implement the main dashboard screen using Shadcn UI and Tailwind CSS, within an estimated 26 hours.

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need (cards, balance, etc). Once all this smaller components are implemented, I'll continue with the dashboard integration as its own component.

**Comment by tosinmoses384** [comment]
I’d like to work on this.

**Comment by derianrddev** [comment]
**Hello PayStell team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. **Analysis and design:**
    - Review the design requirements for the dashboard.
    - Create a layout that includes:
        - A section for **recent activity** (such as recent transactions or actions).
        - A section for prominently displaying the **total sales balance**.
2. **Develop reusable components:**
    - **Activity list or cards**: Create a reusable component to display recent activity.
    - **Balance display**: Create a reusable component to show the total sales balance with proper formatting (e.g., currency format).
3. **Dummy data integration:**
    - Integrate dummy data for testing and ensure it can easily be replaced with real data in the future.
4. **Responsiveness and accessibility validation:**
    - Ensure the dashboard is fully **responsive** and **accessible** across devices.
5. **Component organization:**
    - Components should be reusable and organized within the **dashboard** folder.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by respp** [comment]
Hello!

I have been exploring the repository and its issues these past days, and I feel that I can add value by resolving this issue. I am part of the Dojo community and am excited about the opportunity to make my first contributions to Paystell.

In addition to my experience as a frontend and full-stack developer, I have a strong understanding of UI/UX, which will allow me to create components with an attractive, fully responsive, and accessible design. I will ensure that all requirements described in the issue are met and that the final result aligns with the acceptance criteria. 

Thank you for the opportunity 🚀

**Comment by psychemist** [comment]
Hello. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

I will tackle this issue using these steps:

- Implement the main dashboard layout, dividing it into sections for recent activity and total sales balance.
- Use reusable components for activity cards and balance display with well forrmatted currencies.
- Integrate dummy data for testing and ensure easy future integration with real data.
- Ensure the dashboard is responsive on various devices and meets accessibility standards.
- Ensure that all components are reusable and organized within the dashboard folder for maintainability and scalability.

I aim to complete this task within 36 hours after being assigned and setting up my development environment, with my first pull request submitted before 12 hours. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you.

**Comment by MarcusDavidG** [comment]
with my solid experience with web3 frontend design and knowledge of how smart contracts work, this issue should be as sweet as a piece of cake lol

**Comment by kcmikee** [comment]
Can I take care of this issue?

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.

 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
Additionally, I’m a Gold Contributor with over 15 merged PRs, showcasing my commitment to open-source development and collaborative problem-solving.

To tackle this issue:

Layout Design: Create a dashboard layout with sections for recent activity and prominently displayed total sales balance.
Reusable Components: Develop components for the activity list/cards and balance display with proper currency formatting.
Dummy Data: Use test data for development, ensuring it can be easily replaced with real data later.
Responsiveness: Ensure the dashboard is fully responsive and accessible across all devices.
Component Organization: Structure the components in a dashboard folder for consistency and reusability.
ETA: 12-48 hours.

already contributed to the project, would love to do it again!
Feel free to reach out via Telegram

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Can i work on this?

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by AnoukRImola** [comment]
Hi @MPSxDev, I am Anouk Rímola, I have experience with this issues.

I'd like to work on this issue. After analyzing the project structure, here's how I propose to solve it:
I'll implement the main dashboard following the existing pattern (like`/sales `page), breaking it down into three main components under /components/dashboard/:

1. `DashboardHeader` : With title and general stats
2. `overview/SalesOverview` : Section featuring total balance and trend chart
3. `activity/ActivitySection` : Recent activity table

I'll leverage the existing UI library (Card, Table, Chart) and follow current styling conventions :)

**Comment by codeZe-us** [comment]
Can I handle this task?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by stephanniegb** [comment]
Can I work on this, please? i have 3 years of experience building responsive, performant and pixel perfect UI, i would do great job if i handled this. 
heres how i would do this:
- I would inspect the figma design 
- then create a responsive layout that includes all the sections
- i will develop a reusable component for activity list
- integrate dummy data for testing
- most especially i will make all components responsive
-i will wrap up for testing that all components looks great on all screen sizes and make sure it looks great on all common browsers

Here are some of my recent projects for your reference:                                                                                                - https://tba-frontend-eta.vercel.app 
- https://scroll-transform-recreate.vercel.app
- https://three-js-galaxy-silk.vercel.app/

**Comment by Amarjeet325** [comment]
i am a MERN Stack Developer builds full-stack web applications using MongoDB, Express.js, React.js, and Node.js. They specialize in creating scalable, dynamic, and efficient web solutions. May I try my hand at this? Thank you !

**Comment by TheSQLguy** [comment]
Hey, I am new to open source and would love to contribute.
I will design sections for recent activity and total sales balance into the main dashboard. The reusable components for the activity list and balance display will be created so that later they can easily be updated with real data. Dummy data will be integrated for testing purposes, and the layout will be validated for responsiveness and accessibility across devices. Code will be organized in the dashboard folder according to specifications.

**Comment by web3normad** [comment]
Hi, I'm Emmanuel and I am a thorough frontend dev with expert skills in react, typescript and tailwindcss. I can create this design in 2hrs if given the job.

**Comment by sebas11042** [comment]
Background:
I am a software developer with experience in Java, JavaScript, React, and C#, and I am an active member of the Dojo Coding community. As part of the Sunset Labs team, I have worked on developing on-chain games, gaining valuable experience in creating reusable and responsive components for dashboards and user interfaces. My experience with currency formatting, accessibility, and adhering to Figma design specifications ensures that I can deliver a polished and functional dashboard that meets all requirements and aligns with the project's goals.

Solution:
To implement the main dashboard for the application, I will create a layout that includes a section for displaying recent activity (e.g., recent transactions or actions) and a prominently displayed section for the total sales balance. I will develop reusable components for the activity list and the balance display, ensuring proper formatting (e.g., currency). Dummy data will be integrated for testing purposes, allowing for easy replacement with real data in the future. The dashboard will be fully responsive and accessible, adhering to modern web development standards, and will be implemented as a separate component to maintain consistency across the project.

**Comment by Supa-mega** [comment]
I’d love to work on this task.

**Comment by obah** [comment]
Hi, I am Obaloluwa, a frontend developer with over 2 years of experience, using React, NextJs, typescript and tailwindCSS regularly and I am well familiar with creating dashboard pages like the one in this task.

Can I work on this issue?

My plan to handle this issue:
1. I will study the design to know all the requirements and components I need to create, then familarize myself with the code base to get the structure and tools used.
2. Next is I will create all the required ui components for the form, ensuring they are resuable, responsive, accessible and match the design perfectly.
3. Then, implement the dashboard screen for this task, ensure its functional and tested with dummy data.

ETA: 1 to 2 days.

I will be sure to communicate with the team on telegram if I face any blockers and would create a PR once I am done.

**Comment by emmz3230** [comment]
Can I attempt this issue?

Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will interpret the design well using the icon and making it responsive for different screens.

**Comment by kcmikee** [comment]
I am kcmikee, a frontend developer with 4+ years of experience working with React, Next.js, and TypeScript. I am a graduate of Web3bridge Africa, where I got to dive deep into blockchain development and contribute to some cool web3 projects. I have also made significant contributions to open-source projects and am eager to bring that expertise to this project.

My approach to this task will include:
1. Create a layout that includes:
 - A section for recent activity, like transactions or user actions.
 - A section that prominently displays the total sales balance.

2. Develop the activity list or cards that'll show balance in the proper currency format
3. Integrate dummy data for testing, keeping it simple to swap out with real data later.
4. Validate the design for responsiveness and accessibility across all devices.


Estimated Time (ET): 1 day.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and reference design. I believe this is an excellent first issue for me to contribute to. Can take on this task?
