### ISSUE TITLE
Initialize project with Next.js

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#4]
- Set up the project frontend using Next.js.
- Initialize the frontend with Next.js as the starting point.
- Add a Markdown file with instructions to run the frontend.
- If you need the logo in .svg you can request it by telegram or any other query.

Technical Implementation:

- Next.js 14
- TypeScript
- [TailwindCSS](https://tailwindcss.com/)
- [shadcn/ui ](https://ui.shadcn.com/)
- [Class Variance Authority](https://cva.style/docs)
- [Radix UI ](https://www.radix-ui.com/)
- [Lucide](https://lucide.dev/icons/) 

(If you have another better technological implementation, propose it.)

The goal is to initially invite small businesses to implement Paystell as a payment method in their stores. Each business will have a customized payment gateway with its own branding, allowing them to set transaction amounts and accept payments in their local currency equivalent.

**Comment by jsandinoDev** [comment]
Hi @MPSxDev  is this issue open to collaborations?

**Comment by jsandinoDev** [comment]
Hi @MPSxDev  I'm a full stack developer memeber of Dojo Coding with experience in others Web3 projects like Shinigami, GoStarkme, etc.
I would like to contribute on this issue!

**Comment by MPSxDev** [comment]
> Hi @MPSxDev I'm a full stack developer memeber of Dojo Coding with experience in others Web3 projects like Shinigami, GoStarkme, etc. I would like to contribute on this issue!

The issue is yours, if you need anything, contact me by telegram
