### ISSUE TITLE
Refactor PaymentLinkScreen/page.tsx to Use Components and Dynamic Variables

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#40]
## 📘 Issue Description
Refactor the `PaymentLinkScreen/page.tsx` file to follow a component-based structure. Place the components in the components/module/paymentlinkscreen folder and introduce variables to enable dynamic implementation for different payment links in the future.

## 🔍 Steps

1. Analyze the current PaymentLinkScreen/page.tsx file to identify reusable sections.
2. Create a folder named components/paymentlinkscreen to store these components.
3. Replace hardcoded values with variables or props that can be dynamically assigned for different payment links.
4. Update the PaymentLinkScreen/page.tsx to import and use the new components.

## ✅ Acceptance Criteria

- The page is refactored into reusable components stored in components/paymentlinkscreen.
- Hardcoded values are replaced with variables or props.
- The refactored page matches the current design and functionality.
- Components are easily extendable for dynamic implementation.
- No functionality is broken during the refactoring process.

## 🌎 References
Original file: [PaymentLinkScreen/page.tsx](https://github.com/PayStell/paystell-website/blob/main/paystell-frontend/src/app/PaymentLinkScreen/page.tsx)

## 📜 Additional Notes
Follow the existing coding standards and style guidelines for the project.

**Comment by MarcusDavidG** [comment]
I’d like to work on this.

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.

 I value clear communication and constructive feedback, as I believe they are key to collaborative success.

**Comment by NueloSE** [comment]
I'd like to take this issue.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by davedumto** [comment]
Hi, my name is David, and I am skilled in JavaScript, TypeScript, Tailwind CSS, and ShadCN.
To refactor the PaymentLinkScreen/page.tsx file, I will analyze the existing structure to identify reusable sections. I will create a component-based structure, moving these components into the components/paymentlinkscreen folder. Hardcoded values will be replaced with variables or props to enable dynamic implementation for different payment links while ensuring the current design and functionality are preserved.
ETA: 3 days.
Thank you for considering my application!

**Comment by TheSQLguy** [comment]
I am new to open source.
I will refactor the payment link screen/page.tsx by analyzing its current structure and identifying reusable sections. I will create components inside the components/paymentlinkscreen folder and replace hardcoded values with dynamic variables or props. After refactoring, the page will maintain its design as well as functionality but at the same time be extensible for future payment links.

**Comment by A6dulmalik** [comment]
I'd love to work on this! I am Abdulmalik a react front end developer conversant with java script and typescript. I am a new contributor and would like the opportunity to work on this.

**Comment by sonkeydotcom** [comment]
Hello, I’d be thrilled to take this. ETA 48hrs
