### ISSUE TITLE
Integrate the logo into the navbar code on the dashboard

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#41]
## 📘 Issue Description
Implement the logo in .SVG format at the top of the current navbar. The logo should be responsive, ensuring proper visibility on mobile devices, tablets, and desktops without affecting the navbar's functionality.

## 🔍 Steps

1. Request the .SVG logo file.
2. Add the logo to the navbar code, placing it at the top.
3. Ensure the logo adjusts correctly to the container size and is responsive.
4. Test the logo on different screen resolutions and devices (mobile, tablet, desktop).
5. Verify that the navbar's layout and functionality remain unaffected.

## ✅ Acceptance Criteria

- The .SVG logo is correctly displayed at the top of the navbar.
- The logo is responsive and adapts to different screen sizes.
- The navbar's functionality is preserved across devices.
- No performance issues arise when loading the logo.

## 🌎 References
[Logo PayStell](https://drive.google.com/drive/folders/1guq8XbHBAwVjU-synkgdrNG5ti8dimZr?usp=drive_link)

## 📜 Additional Notes
Ensure the navbar layout is not disrupted by the addition of the logo.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by Prosper1218** [comment]
Hello, I'm prosper. I'm a frontend/Blockchain developer with years of experience. 
If this issue is assigned to me, I'll : 
-review the UI.
-Ensure the logo is in perfect size across all screen sizes.
This will take me a maximum of 2 days to achieve. 
Assign this issue to me and let me do what I do best.

**Comment by MarcusDavidG** [comment]
with my solid experience with web3 frontend design and knowledge of how smart contracts work, this issue should be as sweet as a piece of cake lol

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by Michaelkingsdev** [comment]
May I take this issue on?

**Comment by NueloSE** [comment]
I'd be happy to do this.

**Comment by akintola4** [comment]
requested to see the logo and i want to do this so i can contribute more to the community even if not rewarded just doing it matters to me

**Comment by DanielEmmanuel1** [comment]
Is this issue still available?

**Comment by TheSQLguy** [comment]
Si, I will add the logo in.SVG format at the top of the navbar. I will get the logo file first, then ensure that the logo is responsive and properly fits the different screen sizes (mobile, tablet, desktop) without affecting the functionality of the navbar. I will also test on various devices to ensure smooth performance and layout consistency.

**Comment by devJaja** [comment]
I’m interested in this one.
I am a smart contract frontend Developer, I'm very familier with typescript, I can solve this issue by following the steps mention above, using tailwind css and making it responsive on all device screen

**Comment by A6dulmalik** [comment]
Is it okay if I tackle this? The above issue fits my skill and can deliver following the clear instructions above. Kindly assign.

**Comment by kcmikee** [comment]
I am kcmikee, a frontend developer with 4+ years of experience working with React, Next.js, and TypeScript. I am a graduate of Web3bridge Africa, where I got to dive deep into blockchain development and contribute to some cool web3 projects. I have also made significant contributions to open-source projects and am eager to bring that expertise to this project.
My approach to this task will include:

1. Request the .SVG logo file.
2. Add the logo to the navbar code, placing it at the top.
3. Ensure the logo adjusts correctly to the container size and is responsive.
4. Test the logo on different screen resolutions and devices (mobile, tablet, desktop).
5. Verify that the navbar's layout and functionality remain unaffected.

Estimated Time (ET): 2hrs.

**Comment by Superior212** [comment]
Hey! I'm Superior,
I'm a member of BuidlGuidl and have contributed to various projects such as:
CoinSafe
Web3Bridge
GuildAudit
I haven’t contributed to any OnlyDust projects yet, but I’m eager to use my experience to make a strong impact on this task.
Plan to Solve the Issue:
Study the Codebase: I’ll review the existing structure and functionality to understand the current implementation.
Understand the Problem: I’ll carefully read the issue details to comprehend the task at hand fully.
Leverage Resources: I’ll utilize any provided resources or references within the issue to guide my solution.
Seek Clarifications: If I encounter challenges, I’ll ask questions in the Telegram group to ensure steady progress.
Submit PR: Once the solution is implemented, I’ll open a pull request and await your feedback.
I’m excited to contribute and am confident in my ability to solve this issue effectively!

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.
