### ISSUE TITLE
Add contributors guide

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#5]
We need to implement a contributors guide for new contributors.
Feel free to propose.

**Comment by derianrddev** [comment]
Hi, I'm Derian, a fullstack developer and I'm Dojo Coding member.

Previously, I participated in creating the contribution guide for the Semaphore Stellar documentation project, and I would like to contribute to this project.

**Comment by sandragcarrillo** [comment]
Would love to solve this issue, I have been contributing to other Open Source projects in the past and have a clear idea on how the contributors guide should be.

**Comment by LazarusAA** [comment]
## My background

Hi, I'm Alvaro Lazarus a blockchain developer and member of Dojo Coding, I'd love to work on this Issue and contribute to PayStell.

## How I would resolve this 

I’ll provide clear guidelines for contributing to the repository, including steps for creating issues, forking, and naming best practices to help new contributors follow a consistent process.

ETA: 24 hrs

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda. 
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3. 
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To approach this issue, I’d create a structured Contributors Guide for new contributors, drawing on my experience developing documentation for two projects, including a README and issue template. The guide could outline essential contribution steps, coding standards, and provide a sample pull request process. I’d also propose sections on setting up the environment, testing practices, and frequently asked questions to address common hurdles new contributors might face.

**Comment by salazarsebas** [comment]
My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have managed to make a contribution, however, it is not an impediment for me to do my best in this issue, I will devote the necessary effort to contribute to the OSS.

How I plan on tackling this issue
To solve this issue, I will perform the following steps:

- Make a contribution guide where it is well explained but at the same time concise.
- Visually pleasing.
- Place the different types of branches (feat, fix, docs, among others).
- End the guide with a thank you for using the guide and maintain a nomenclature in the project.
